name: Deploy Testing VM

on:
  push:
    branches:
      - '**'
      - '!main'
jobs:

  deploy-debian-vm-azure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      run:  curl https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip -o testing/on_vm/terraform/terraform.zip
    - name: Unzipping Terraform
      run: unzip testing/on_vm/terraform/terraform.zip -d testing/on_vm/terraform/ && \
      chmod +x testing/on_vm/terraform/terraform && \
      mv testing/on_vm/terraform/terraform /usr/local/bin/terraform
    - name: Run Terraform Plan
      run: export ARM_CLIENT_ID=${{ ARM_CLIENT_ID }} && \
      export ARM_CLIENT_SECRET=${{ ARM_CLIENT_SECRET }} && \
      export ARM_SUBSCRIPTION_ID=${{ ARM_SUBSCRIPTION_ID }} && \
      export ARM_TENANT_ID=${{ ARM_TENANT_ID }} && \
      export ARM_ACCESS_KEY=${{ ARM_ACCESS_KEY }} && \
      cd testing/on_vm/terraform/ && \
      terraform init && \
      terraform plan -out=testing/on_vm/terraform/planfile
