name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run:  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -P ${{ secrets.DOCKERHUB_TOKEN  }}
    - name: Build the Docker image
      run: docker build testing/api/ --file Dockerfile --tag reiniernel89/relayctl:test-api
    - name: Push Docker image to Docker Hub
      run: docker push reiniernel89/relayctl:test-api
