name: Docker Build and Push CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run:  docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN  }} 
    - name: Build the Docker image
      #run: docker build /home/runner/work/relayctl/relayctl/testing/api/ --file Dockerfile --tag reiniernel89/relayctl:test-api
      run: pwd && ls -la
    - name: Push Docker image to Docker Hub
      #run: docker push reiniernel89/relayctl:test-api
